-- Stock Clearance 2025 (35) & 2026 (104) Exhibitors SQL Data

-- Clean up duplicate dashain-fest event if exists
DELETE FROM public."Exhibitor" WHERE "editionId" IN (SELECT id FROM public."ExhibitorEdition" WHERE "eventId" IN (SELECT id FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest'));
DELETE FROM public."ExhibitorEdition" WHERE "eventId" IN (SELECT id FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest');
DELETE FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest';

-- Ensure Stock Clearance event exists
INSERT INTO public."ExhibitorEvent" (slug, title, "chronicleNumber", description, "previewImage", "order", "createdAt", "updatedAt")
VALUES ('stock-clearance', 'Stock Clearance', '04', 'Nepal''s premier consumer shopping, clearance festival, and festive carnival connecting leading manufacturers, retail distributors, and domestic brands directly with shoppers.', 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80', 3, NOW(), NOW())
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title;

-- Ensure Editions and seed exhibitors
DO $$
DECLARE
    v_event_id INT;
    v_edition_2025_id INT;
    v_edition_2026_id INT;
BEGIN
    SELECT id INTO v_event_id FROM public."ExhibitorEvent" WHERE slug = 'stock-clearance';
    
    -- 2025 Edition (35 Exhibitors)
    SELECT id INTO v_edition_2025_id FROM public."ExhibitorEdition" WHERE "eventId" = v_event_id AND year = '2025';
    IF v_edition_2025_id IS NULL THEN
        INSERT INTO public."ExhibitorEdition" (year, title, dates, venue, attendees, "previewImage", "order", "eventId", "createdAt", "updatedAt")
        VALUES ('2025', 'Edition 2025 (Dashain Fest)', 'Dashain Season 2025', 'Bhrikutimandap Exhibition Ground, Kathmandu', '120K+', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80', 2, v_event_id, NOW(), NOW())
        RETURNING id INTO v_edition_2025_id;
    END IF;

    DELETE FROM public."Exhibitor" WHERE "editionId" = v_edition_2025_id;

    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-udhami-ghar', 'UDHAMI GHAR', '/company/Screenshot_2026-10-04_at_5_50_30_PM_1791116825418_wtqm.png', 'Luniva Joshi', '9801765419', '', '', 'Stall 4 (3M X 3M)', 'Festive & Consumer Trade', 'UDHAMI GHAR at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 4 (3M X 3M).', '[]', '', '', '', 0, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-sarangi-bedsheet', 'SARANGI BEDSHEET', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Nischhet Rawal', '9818626800', '', '', 'Stall 6 (3M X 3M)', 'Festive & Consumer Trade', 'SARANGI BEDSHEET at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 6 (3M X 3M).', '[]', '', '', '', 1, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-diamond-knitland', 'DIAMOND KNITLAND', '/company/Screenshot_2026-10-04_at_5_50_39_PM_1791116825421_oomt.png', 'Biju Shakya', '9851024416', '', '', 'Stall 7 (3M X 3M)', 'Festive & Consumer Trade', 'DIAMOND KNITLAND at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 7 (3M X 3M).', '[]', '', '', '', 2, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-arksh-group', 'ARKSH GROUP', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Diwas', '9704591211', '', '', 'Stall 9 (6M X 3M)', 'Festive & Consumer Trade', 'ARKSH GROUP at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 9 (6M X 3M).', '[]', '', '', '', 3, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-nepal-cotton-house', 'NEPAL COTTON HOUSE', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Milan Malakar', '9851030591', '', '', 'Stall 10 (3M X 3M)', 'Festive & Consumer Trade', 'NEPAL COTTON HOUSE at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 10 (3M X 3M).', '[]', '', '', '', 4, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-silver-6-warm-oil', 'SILVER 6 WARM OIL', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Nirajan Oli', '9806297473', '', '', 'Stall 18 (6M X 3M)', 'Festive & Consumer Trade', 'SILVER 6 WARM OIL at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 18 (6M X 3M).', '[]', '', '', '', 5, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-gau-sahar-samuhik-mahila-udhyam', 'GAU SAHAR SAMUHIK MAHILA UDHYAM', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Indira Rai', '9847338353', '', '', 'Stall 21A (3M X 2M)', 'Festive & Consumer Trade', 'GAU SAHAR SAMUHIK MAHILA UDHYAM at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 21A (3M X 2M).', '[]', '', '', '', 6, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-r-a-jewelers', 'R.A JEWELERS', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 21B (3M X 2M)', 'Festive & Consumer Trade', 'R.A JEWELERS at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 21B (3M X 2M).', '[]', '', '', '', 7, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-loom-of-nepal', 'LOOM OF NEPAL', '/uploads/exhibitors/logos/73569a39-0752-47e5-842b-12a40f65055b-Screenshot2026-10-04at5.44.19PM.png', 'Anup Shrestha', '', '', '', 'Stall 22A (3M X 2M)', 'Festive & Consumer Trade', 'LOOM OF NEPAL at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 22A (3M X 2M).', '[]', '', '', '', 8, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-euphoria-nepal', 'EUPHORIA NEPAL', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 23A (3M X 2M)', 'Festive & Consumer Trade', 'EUPHORIA NEPAL at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 23A (3M X 2M).', '[]', '', '', '', 9, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-gypsy-collection', 'GYPSY COLLECTION', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Chanda Khadka', '9851021939', '', '', 'Stall 23B (3M X 2M)', 'Festive & Consumer Trade', 'GYPSY COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 23B (3M X 2M).', '[]', '', '', '', 10, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-shreem-leather-wosa-wear', 'SHREEM LEATHER/ WOSA WEAR', '/company/Screenshot%202025-12-28%20at%201.31.41%E2%80%AFPM.png', 'Gyanab Shrestha', '9841243840', '', '', 'Stall 25 (6M X 3M)', 'Festive & Consumer Trade', 'SHREEM LEATHER/ WOSA WEAR at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 25 (6M X 3M).', '[]', '', '', '', 11, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-dora-collection', 'DORA COLLECTION', '/company/Screenshot%202025-12-28%20at%201.31.46%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 26A (3M X 3M)', 'Festive & Consumer Trade', 'DORA COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 26A (3M X 3M).', '[]', '', '', '', 12, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-simrik-collection', 'SIMRIK COLLECTION', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 26B (3M X 3M)', 'Festive & Consumer Trade', 'SIMRIK COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 26B (3M X 3M).', '[]', '', '', '', 13, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-hamro-wear', 'HAMRO WEAR', '/company/Screenshot_2026-10-04_at_5_53_58_PM_1791116825465_ic58.png', 'Soni Thapa', '', '', '', 'Stall 27 (3M X 3M)', 'Festive & Consumer Trade', 'HAMRO WEAR at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 27 (3M X 3M).', '[]', '', '', '', 14, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-aaradhya-gifts-pvt-ltd-jharna-ko-vansa', 'AARADHYA GIFTS PVT. LTD/ JHARNA KO VANSA', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Exhibition Manager', '', '', '', 'Stall 16 (3M X 3M)', 'Festive & Consumer Trade', 'AARADHYA GIFTS PVT. LTD/ JHARNA KO VANSA at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 16 (3M X 3M).', '[]', '', '', '', 15, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-hak-traders', 'HAK TRADERS', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 38 (3M X 3M)', 'Festive & Consumer Trade', 'HAK TRADERS at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 38 (3M X 3M).', '[]', '', '', '', 16, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-nityam-argo-industry-pvt-ltd', 'NITYAM ARGO INDUSTRY PVT. LTD', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Exhibition Manager', '', '', '', 'Stall 18 (3M X 3M)', 'Festive & Consumer Trade', 'NITYAM ARGO INDUSTRY PVT. LTD at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 18 (3M X 3M).', '[]', '', '', '', 17, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-krisha-collection', 'KRISHA COLLECTION', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 41 (6M X 3M)', 'Festive & Consumer Trade', 'KRISHA COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 41 (6M X 3M).', '[]', '', '', '', 18, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-worth-it-wears', 'WORTH IT WEARS', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall 42A (3M X 3M)', 'Festive & Consumer Trade', 'WORTH IT WEARS at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 42A (3M X 3M).', '[]', '', '', '', 19, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-pkg-international-pvt-ltd', 'PKG INTERNATIONAL PVT. LTD', '/company/Screenshot_2026-10-04_at_5_50_34_PM_1791116825418_o124.png', 'Ganesh Gurung', '9818971445', '', '', 'Stall 43 (3M X 3M)', 'Festive & Consumer Trade', 'PKG INTERNATIONAL PVT. LTD at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 43 (3M X 3M).', '[]', '', '', '', 20, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-prabisati-products-p-ltd', 'PRABISATI PRODUCTS (P) LTD.', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Basanti', '9849191068', '', '', 'Stall 44 (3M X 3M)', 'Festive & Consumer Trade', 'PRABISATI PRODUCTS (P) LTD. at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 44 (3M X 3M).', '[]', '', '', '', 21, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-the-classy-closet', 'THE CLASSY CLOSET', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Vicky Modi', '9803772700 / 9704474290', '', '', 'Stall 46 (3M X 3M)', 'Festive & Consumer Trade', 'THE CLASSY CLOSET at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 46 (3M X 3M).', '[]', '', '', '', 22, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-royal-leather', 'ROYAL LEATHER', '/company/Screenshot_2026-10-04_at_5_53_10_PM_1791116825454_7y9i.png', 'Anup Shrestha', '', '', '', 'Stall 47A (3M X 3M)', 'Festive & Consumer Trade', 'ROYAL LEATHER at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 47A (3M X 3M).', '[]', '', '', '', 23, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-readymade', 'READYMADE', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 47B (3M X 3M)', 'Festive & Consumer Trade', 'READYMADE at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 47B (3M X 3M).', '[]', '', '', '', 24, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-kiddos-nepal', 'KIDDOS NEPAL', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 48B (3M X 3M)', 'Festive & Consumer Trade', 'KIDDOS NEPAL at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 48B (3M X 3M).', '[]', '', '', '', 25, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-sayamee', 'SAYAMEE', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Anup Shrestha', '9803631200', '', '', 'Stall 48A (3M X 3M)', 'Festive & Consumer Trade', 'SAYAMEE at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 48A (3M X 3M).', '[]', '', '', '', 26, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-s-factories', 'S. FACTORIES', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Supriya Khatiwada', '9801118491', '', '', 'Stall 50 (5M X 3M)', 'Festive & Consumer Trade', 'S. FACTORIES at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 50 (5M X 3M).', '[]', '', '', '', 27, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-jari-traditional', 'JARI TRADITIONAL', '/company/Screenshot_2026-10-04_at_5_50_58_PM_1791116825424_f39r.png', 'Luniva Joshi', '9705199601', '', '', 'Stall 54 (3M X 3M)', 'Festive & Consumer Trade', 'JARI TRADITIONAL at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 54 (3M X 3M).', '[]', '', '', '', 28, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-tera-collection', 'TERA COLLECTION', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Anup Shrestha', '9851069770', '', '', 'Stall 55 (3M X 3M)', 'Festive & Consumer Trade', 'TERA COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 55 (3M X 3M).', '[]', '', '', '', 29, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-nevan-collection', 'NEVAN COLLECTION', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Anjana Shrestha', '9861285382', '', '', 'Stall 56 (3M X 3M)', 'Festive & Consumer Trade', 'NEVAN COLLECTION at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 56 (3M X 3M).', '[]', '', '', '', 30, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-milk-art-and-food-product-pvt-ltd', 'MILK ART AND FOOD PRODUCT PVT. LTD', '/uploads/exhibitors/logos/3f72ecdd-85a1-4e72-bd7c-4d9e68422be7-Screenshot2026-10-04at5.44.16PM.png', 'Bibas Kafle', '9843699090', '', '', 'Stall 57 (3M X 3M)', 'Festive & Consumer Trade', 'MILK ART AND FOOD PRODUCT PVT. LTD at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 57 (3M X 3M).', '[]', '', '', '', 31, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-feather-apparels', 'Feather Apparels', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 61 (3M X 3M)', 'Festive & Consumer Trade', 'Feather Apparels at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 61 (3M X 3M).', '[]', '', '', '', 32, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-nut-fun-koseli', 'NUT FUN KOSELI', '/company/Screenshot%202025-12-28%20at%201.31.57%E2%80%AFPM.png', 'Anup Shrestha', '9840365475', '', '', 'Stall 62 (3M X 3M)', 'Festive & Consumer Trade', 'NUT FUN KOSELI at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 62 (3M X 3M).', '[]', '', '', '', 33, v_edition_2025_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2025-gau-ghar-chautari-bazar-pvt-ltd', 'GAU GHAR CHAUTARI BAZAR PVT.LTD', '/company/Screenshot%202025-12-28%20at%201.32.58%E2%80%AFPM.png', 'Anup Shrestha', '9851459533', '', '', 'Stall 64 (3M X 3M)', 'Festive & Consumer Trade', 'GAU GHAR CHAUTARI BAZAR PVT.LTD at Stock Clearance 2025', 'Participating brand exhibitor at Stock Clearance (Dashain Fest) 2025. Stall 64 (3M X 3M).', '[]', '', '', '', 34, v_edition_2025_id, NOW(), NOW(), 'APPROVED');

    -- 2026 Edition (104 Exhibitors)
    SELECT id INTO v_edition_2026_id FROM public."ExhibitorEdition" WHERE "eventId" = v_event_id AND year = '2026';
    IF v_edition_2026_id IS NULL THEN
        INSERT INTO public."ExhibitorEdition" (year, title, dates, venue, attendees, "previewImage", "order", "eventId", "createdAt", "updatedAt")
        VALUES ('2026', 'Edition 2026 (Dashain Fest)', 'Dashain Season 2026', 'Bhrikutimandap Exhibition Ground, Kathmandu', '150K+', 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80', 3, v_event_id, NOW(), NOW())
        RETURNING id INTO v_edition_2026_id;
    END IF;

    DELETE FROM public."Exhibitor" WHERE "editionId" = v_edition_2026_id;

    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-tera-collection', 'Tera Collection', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 1 (3M X 3M)', 'Festive & Consumer Trade', 'Tera Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 1 (3M X 3M).', '[]', '', '', '', 0, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nepal-cotton-house', 'Nepal Cotton House', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 2 (3M X 3M)', 'Festive & Consumer Trade', 'Nepal Cotton House at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 2 (3M X 3M).', '[]', '', '', '', 1, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-heera-enterprise-bangladesh', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 3 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 3 (3M X 3M).', '[]', '', '', '', 2, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-eras-feel', 'Eras Feel', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Manisha', '986-3253251', '', '', 'Stall 4 (3M X 3M)', 'Festive & Consumer Trade', 'Eras Feel at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 4 (3M X 3M).', '[]', '', '', '', 3, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-opseri-boutique-bangladesh', 'Opseri Boutique (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 5 (3M X 3M)', 'Festive & Consumer Trade', 'Opseri Boutique (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 5 (3M X 3M).', '[]', '', '', '', 4, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-kohinoor-knitwear-bangladesh', 'Kohinoor Knitwear (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 6 (3M X 3M)', 'Festive & Consumer Trade', 'Kohinoor Knitwear (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 6 (3M X 3M).', '[]', '', '', '', 5, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-soft-skin-pakistan', 'Soft Skin (Pakistan)', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 7 (3M X 3M)', 'Festive & Consumer Trade', 'Soft Skin (Pakistan) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 7 (3M X 3M).', '[]', '', '', '', 6, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-pinky-fashion', 'Pinky Fashion', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 8 (3M X 3M)', 'Festive & Consumer Trade', 'Pinky Fashion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 8 (3M X 3M).', '[]', '', '', '', 7, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-toys-world', 'Toys World', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall 9 (6M X 3M)', 'Festive & Consumer Trade', 'Toys World at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 9 (6M X 3M).', '[]', '', '', '', 8, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nihan-traders-china', 'Nihan Traders (China)', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 10 (6M X 3M)', 'Festive & Consumer Trade', 'Nihan Traders (China) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 10 (6M X 3M).', '[]', '', '', '', 9, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-bluemen-bangladesh', 'Bluemen (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 11 (3M X 3M)', 'Festive & Consumer Trade', 'Bluemen (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 11 (3M X 3M).', '[]', '', '', '', 10, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-heera-enterprise-bangladesh-stall-12-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 12 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 12 (3M X 3M).', '[]', '', '', '', 11, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-heera-enterprise-bangladesh-stall-13-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 13 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 13 (3M X 3M).', '[]', '', '', '', 12, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-heera-enterprise-bangladesh-stall-14-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 14 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 14 (3M X 3M).', '[]', '', '', '', 13, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-heera-enterprise-bangladesh-stall-15-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 15 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 15 (3M X 3M).', '[]', '', '', '', 14, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-pakistan-pavilion', 'Pakistan Pavilion', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 16 (3M X 3M)', 'Festive & Consumer Trade', 'Pakistan Pavilion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 16 (3M X 3M).', '[]', '', '', '', 15, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-kiddo', 'Kiddo', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Suparbha Shrestha', '9841919262', '', '', 'Stall 17 (3M X 3M)', 'Festive & Consumer Trade', 'Kiddo at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 17 (3M X 3M).', '[]', '', '', '', 16, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-bangladesh-pavilion', 'Bangladesh Pavilion', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 18 (6M X 3M)', 'Festive & Consumer Trade', 'Bangladesh Pavilion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 18 (6M X 3M).', '[]', '', '', '', 17, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-nepal', 'Shoes Nepal', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Krishtina', '9811821331', '', '', 'Stall 19 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Nepal at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 19 (3M X 3M).', '[]', '', '', '', 18, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-expo-section-a', 'Shoes Expo Section A', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 20 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section A at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 20 (3M X 3M).', '[]', '', '', '', 19, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-expo-section-b', 'Shoes Expo Section B', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 21 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section B at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 21 (3M X 3M).', '[]', '', '', '', 20, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-expo-section-c', 'Shoes Expo Section C', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 22 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section C at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 22 (3M X 3M).', '[]', '', '', '', 21, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-saurab', 'Saurab', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 23 (6M X 3M)', 'Festive & Consumer Trade', 'Saurab at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 23 (6M X 3M).', '[]', '', '', '', 22, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-al-madina', 'Al-Madina', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 24 (6M X 3M)', 'Festive & Consumer Trade', 'Al-Madina at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 24 (6M X 3M).', '[]', '', '', '', 23, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-store', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 25 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 25 (3M X 3M).', '[]', '', '', '', 24, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-store-stall-26-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 26 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 26 (3M X 3M).', '[]', '', '', '', 25, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-your-readymade', 'Your Readymade', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 27 (3M X 3M)', 'Festive & Consumer Trade', 'Your Readymade at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 27 (3M X 3M).', '[]', '', '', '', 26, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nitya-traditional-trader', 'Nitya Traditional Trader', '/company/Screenshot%202025-12-28%20at%201.31.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 28 (3M X 3M)', 'Festive & Consumer Trade', 'Nitya Traditional Trader at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 28 (3M X 3M).', '[]', '', '', '', 27, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-bangladesh-trade-store', 'Bangladesh Trade Store', '/company/Screenshot%202025-12-28%20at%201.31.46%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 29 (3M X 3M)', 'Festive & Consumer Trade', 'Bangladesh Trade Store at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 29 (3M X 3M).', '[]', '', '', '', 28, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-mousami-saari-india-fairy-angel-bangladesh', 'Mousami Saari (India) / Fairy Angel (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 30 (6M X 3M)', 'Festive & Consumer Trade', 'Mousami Saari (India) / Fairy Angel (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 30 (6M X 3M).', '[]', '', '', '', 29, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-sandhya-furniture-india', 'Sandhya Furniture (India)', '/company/Screenshot%202025-12-28%20at%201.31.57%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 31 (6M X 3M)', 'Festive & Consumer Trade', 'Sandhya Furniture (India) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 31 (6M X 3M).', '[]', '', '', '', 30, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-simrik-collection', 'Simrik Collection', '/company/Screenshot%202025-12-28%20at%201.32.47%E2%80%AFPM.png', 'Monalika Bhattarai', '', '', '', 'Stall 32 (3M X 3M)', 'Festive & Consumer Trade', 'Simrik Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 32 (3M X 3M).', '[]', '', '', '', 31, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-k-nav-collection', 'K.nav Collection', '/company/Screenshot%202025-12-28%20at%201.32.58%E2%80%AFPM.png', 'Monalika Bhattarai', '9860286644', '', '', 'Stall 33 (3M X 3M)', 'Festive & Consumer Trade', 'K.nav Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 33 (3M X 3M).', '[]', '', '', '', 32, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-anish-clothing', 'Anish Clothing', '/company/Screenshot%202025-12-28%20at%201.33.04%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall 34 (3M X 3M)', 'Festive & Consumer Trade', 'Anish Clothing at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 34 (3M X 3M).', '[]', '', '', '', 33, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-store-stall-35-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.33.10%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 35 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 35 (3M X 3M).', '[]', '', '', '', 34, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-store-stall-36-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.33.20%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 36 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 36 (3M X 3M).', '[]', '', '', '', 35, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-arksh-group', 'Arksh Group', '/company/Screenshot%202025-12-28%20at%201.33.29%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 37 (6M X 3M)', 'Festive & Consumer Trade', 'Arksh Group at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 37 (6M X 3M).', '[]', '', '', '', 36, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-refer-lifestyle', 'Refer Lifestyle', '/company/Screenshot%202025-12-28%20at%201.33.34%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 38 (6M X 3M)', 'Festive & Consumer Trade', 'Refer Lifestyle at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 38 (6M X 3M).', '[]', '', '', '', 37, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-gallery-a', 'Shoes Gallery A', '/company/Screenshot%202025-12-28%20at%201.40.40%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 39 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery A at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 39 (3M X 3M).', '[]', '', '', '', 38, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-gallery-b', 'Shoes Gallery B', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 40 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery B at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 40 (3M X 3M).', '[]', '', '', '', 39, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-gallery-c', 'Shoes Gallery C', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 41 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery C at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 41 (3M X 3M).', '[]', '', '', '', 40, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shoes-gallery-d', 'Shoes Gallery D', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 42 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery D at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 42 (3M X 3M).', '[]', '', '', '', 41, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-made-in-bangladesh-bangladesh', 'Made in Bangladesh (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 43 (6M X 3M)', 'Festive & Consumer Trade', 'Made in Bangladesh (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 43 (6M X 3M).', '[]', '', '', '', 42, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-g-11-bangladesh', 'G-11 (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 44 (3M X 3M)', 'Festive & Consumer Trade', 'G-11 (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 44 (3M X 3M).', '[]', '', '', '', 43, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-barcilife-bangladesh', 'Barcilife (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 45 (3M X 3M)', 'Festive & Consumer Trade', 'Barcilife (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 45 (3M X 3M).', '[]', '', '', '', 44, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-a-p-zone', 'A.P Zone', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 46 (3M X 3M)', 'Festive & Consumer Trade', 'A.P Zone at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 46 (3M X 3M).', '[]', '', '', '', 45, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-milan-jutta-pasal', 'Milan Jutta Pasal', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 47 (3M X 3M)', 'Festive & Consumer Trade', 'Milan Jutta Pasal at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 47 (3M X 3M).', '[]', '', '', '', 46, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-milan-jutta-pasal-stall-48-1', 'Milan Jutta Pasal', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 48 (3M X 3M)', 'Festive & Consumer Trade', 'Milan Jutta Pasal at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 48 (3M X 3M).', '[]', '', '', '', 47, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-arohan-associate-bangladesh', 'Arohan Associate (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 49 (3M X 3M)', 'Festive & Consumer Trade', 'Arohan Associate (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 49 (3M X 3M).', '[]', '', '', '', 48, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-tera-collection-stall-50-1', 'Tera Collection', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 50 (3M X 3M)', 'Festive & Consumer Trade', 'Tera Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 50 (3M X 3M).', '[]', '', '', '', 49, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-mukti-clothing', 'Mukti Clothing', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 51 (6M X 3M)', 'Festive & Consumer Trade', 'Mukti Clothing at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 51 (6M X 3M).', '[]', '', '', '', 50, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-krisha-collection', 'Krisha Collection', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 52A (3M X 3M)', 'Festive & Consumer Trade', 'Krisha Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 52A (3M X 3M).', '[]', '', '', '', 51, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-sitara-bag-jewellry', 'Sitara Bag & Jewellry', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Meleena Kalikote', '9825755160', '', '', 'Stall 52B (3M X 3M)', 'Festive & Consumer Trade', 'Sitara Bag & Jewellry at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 52B (3M X 3M).', '[]', '', '', '', 52, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shree-collection', 'Shree Collection', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 53 (3M X 3M)', 'Festive & Consumer Trade', 'Shree Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 53 (3M X 3M).', '[]', '', '', '', 53, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-gopal-enterprises', 'Gopal Enterprises', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 54 (3M X 3M)', 'Festive & Consumer Trade', 'Gopal Enterprises at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 54 (3M X 3M).', '[]', '', '', '', 54, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-universal-packaging-industries-pvt-ltd', 'Universal Packaging Industries Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 55 (3M X 3M)', 'Festive & Consumer Trade', 'Universal Packaging Industries Pvt. Ltd at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 55 (3M X 3M).', '[]', '', '', '', 55, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-krisha-collection-hold', 'Krisha Collection (Hold)', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 56 (3M X 3M)', 'Festive & Consumer Trade', 'Krisha Collection (Hold) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 56 (3M X 3M).', '[]', '', '', '', 56, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-n-fashion', 'N Fashion', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 57 (3M X 3M)', 'Festive & Consumer Trade', 'N Fashion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 57 (3M X 3M).', '[]', '', '', '', 57, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nepal-wool-house', 'Nepal Wool House', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 58 (3M X 3M)', 'Festive & Consumer Trade', 'Nepal Wool House at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 58 (3M X 3M).', '[]', '', '', '', 58, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-royal-furniture-udyog', 'Royal Furniture Udyog', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 59 (6M X 3M)', 'Festive & Consumer Trade', 'Royal Furniture Udyog at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall 59 (6M X 3M).', '[]', '', '', '', 59, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-asian-exclusive-bismillah-accessories-bangladesh', 'Asian Exclusive / Bismillah Accessories (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H1 (2M X 4M)', 'Festive & Consumer Trade', 'Asian Exclusive / Bismillah Accessories (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H1 (2M X 4M).', '[]', '', '', '', 60, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-karuka-lamiha-handicraft-bangladesh', 'Karuka / Lamiha Handicraft (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H2 (2M X 4M)', 'Festive & Consumer Trade', 'Karuka / Lamiha Handicraft (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H2 (2M X 4M).', '[]', '', '', '', 61, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-bangladesh-artisan-house', 'Bangladesh Artisan House', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H3 (2M X 4M)', 'Festive & Consumer Trade', 'Bangladesh Artisan House at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H3 (2M X 4M).', '[]', '', '', '', 62, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-europhoria-nepal', 'Europhoria Nepal', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H4 (2M X 2M)', 'Festive & Consumer Trade', 'Europhoria Nepal at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H4 (2M X 2M).', '[]', '', '', '', 63, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-wosa-wears', 'Wosa Wears', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H5 (2M X 2M)', 'Festive & Consumer Trade', 'Wosa Wears at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H5 (2M X 2M).', '[]', '', '', '', 64, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-anandi-jewellery', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H6 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H6 (2M X 2M).', '[]', '', '', '', 65, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-anandi-jewellery-stall-h7-1', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.41%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H7 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H7 (2M X 2M).', '[]', '', '', '', 66, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-anandi-jewellery-stall-h8-1', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.46%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H8 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H8 (2M X 2M).', '[]', '', '', '', 67, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-naya-naulo', 'Naya Naulo', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H9 (2M X 2M)', 'Festive & Consumer Trade', 'Naya Naulo at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H9 (2M X 2M).', '[]', '', '', '', 68, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-pathibhara-art-handicraft', 'Pathibhara Art Handicraft', '/company/Screenshot%202025-12-28%20at%201.31.57%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H10 (2M X 4M)', 'Festive & Consumer Trade', 'Pathibhara Art Handicraft at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H10 (2M X 4M).', '[]', '', '', '', 69, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-ladies-bags-barsha-jung-chettri', 'Ladies Bags / Barsha Jung Chettri', '/company/Screenshot%202025-12-28%20at%201.32.47%E2%80%AFPM.png', 'Barsha Jung Chettri', '', '', '', 'Stall H11 (2M X 2M)', 'Festive & Consumer Trade', 'Ladies Bags / Barsha Jung Chettri at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H11 (2M X 2M).', '[]', '', '', '', 70, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-uma-collection', 'Uma Collection', '/company/Screenshot%202025-12-28%20at%201.32.58%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall H12 (2M X 2M)', 'Festive & Consumer Trade', 'Uma Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H12 (2M X 2M).', '[]', '', '', '', 71, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-bishal-ayurveda', 'Bishal Ayurveda', '/company/Screenshot%202025-12-28%20at%201.33.04%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H13 (2M X 2M)', 'Festive & Consumer Trade', 'Bishal Ayurveda at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H13 (2M X 2M).', '[]', '', '', '', 72, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-arlens-leather-bangladesh', 'Arlens Leather (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.33.10%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H14 (2M X 2M)', 'Festive & Consumer Trade', 'Arlens Leather (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H14 (2M X 2M).', '[]', '', '', '', 73, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shine-chemical', 'Shine Chemical', '/company/Screenshot%202025-12-28%20at%201.33.20%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H15 (2M X 2M)', 'Festive & Consumer Trade', 'Shine Chemical at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H15 (2M X 2M).', '[]', '', '', '', 74, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nevan-collection', 'Nevan Collection', '/company/Screenshot%202025-12-28%20at%201.33.29%E2%80%AFPM.png', 'Grishma Maharjan', '9861285382', '', '', 'Stall H16 (2M X 2M)', 'Festive & Consumer Trade', 'Nevan Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H16 (2M X 2M).', '[]', '', '', '', 75, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nelli', 'Nelli', '/company/Screenshot%202025-12-28%20at%201.33.34%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H17 (2M X 2M)', 'Festive & Consumer Trade', 'Nelli at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H17 (2M X 2M).', '[]', '', '', '', 76, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-padma-chura', 'Padma Chura', '/company/Screenshot%202025-12-28%20at%201.40.40%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H18 (2M X 2M)', 'Festive & Consumer Trade', 'Padma Chura at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H18 (2M X 2M).', '[]', '', '', '', 77, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-adore-home-hold', 'Adore Home (Hold)', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Grishma Maharjan', '9818021462', '', '', 'Stall H19 (2M X 2M)', 'Festive & Consumer Trade', 'Adore Home (Hold) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H19 (2M X 2M).', '[]', '', '', '', 78, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-dora-collection', 'Dora Collection', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H20 (2M X 4M)', 'Festive & Consumer Trade', 'Dora Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H20 (2M X 4M).', '[]', '', '', '', 79, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-kanak-wear', 'Kanak Wear', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H21 (2M X 4M)', 'Festive & Consumer Trade', 'Kanak Wear at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H21 (2M X 4M).', '[]', '', '', '', 80, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-casper-in-out-trading-pvt-ltd', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H22 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H22 (2M X 2M).', '[]', '', '', '', 81, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-poshakana-bangladesh', 'Poshakana (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H23 (2M X 2M)', 'Festive & Consumer Trade', 'Poshakana (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H23 (2M X 2M).', '[]', '', '', '', 82, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-moontain-creamery', 'Moontain Creamery', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Grishma Maharjan', '9764799554', '', '', 'Stall H24 (2M X 2M)', 'Festive & Consumer Trade', 'Moontain Creamery at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H24 (2M X 2M).', '[]', '', '', '', 83, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-casper-in-out-trading-pvt-ltd-stall-h25-1', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H25 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H25 (2M X 2M).', '[]', '', '', '', 84, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-casper-in-out-trading-pvt-ltd-stall-h26-1', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H26 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H26 (2M X 2M).', '[]', '', '', '', 85, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-smart-corporation-bangladesh', 'Smart Corporation (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H27 (2M X 2M)', 'Festive & Consumer Trade', 'Smart Corporation (Bangladesh) at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H27 (2M X 2M).', '[]', '', '', '', 86, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-baladu', 'Baladu', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Grishma Maharjan', '9709061047', '', '', 'Stall H28 (2M X 2M)', 'Festive & Consumer Trade', 'Baladu at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H28 (2M X 2M).', '[]', '', '', '', 87, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-pinky-fashion-stall-h29-1', 'Pinky Fashion', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H29 (2M X 2M)', 'Festive & Consumer Trade', 'Pinky Fashion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H29 (2M X 2M).', '[]', '', '', '', 88, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-nepali-maan-udyog', 'Nepali Maan Udyog', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Grishma Maharjan', '9703093066', '', '', 'Stall H30 (2M X 2M)', 'Festive & Consumer Trade', 'Nepali Maan Udyog at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H30 (2M X 2M).', '[]', '', '', '', 89, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-baladu-stall-h31-1', 'Baladu', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Grishma Maharjan', '9709061047', '', '', 'Stall H31 (2M X 2M)', 'Festive & Consumer Trade', 'Baladu at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H31 (2M X 2M).', '[]', '', '', '', 90, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-suyog-marketing', 'Suyog Marketing', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Malika Sangat', '9843456166', '', '', 'Stall H32 (2M X 2M)', 'Festive & Consumer Trade', 'Suyog Marketing at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H32 (2M X 2M).', '[]', '', '', '', 91, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-7-r-tatooz', '7 R Tatooz', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Monalika Bhattarai', '9847293753', '', '', 'Stall H33 (2M X 2M)', 'Festive & Consumer Trade', '7 R Tatooz at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H33 (2M X 2M).', '[]', '', '', '', 92, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-jamuna-collection', 'Jamuna Collection', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H34 (2M X 2M)', 'Festive & Consumer Trade', 'Jamuna Collection at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H34 (2M X 2M).', '[]', '', '', '', 93, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-ujwol-boutique', 'Ujwol Boutique', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall H35 (2M X 2M)', 'Festive & Consumer Trade', 'Ujwol Boutique at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H35 (2M X 2M).', '[]', '', '', '', 94, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-khaling-craft-jishnu-ayurnidhi-enterprise', 'Khaling Craft / Jishnu Ayurnidhi Enterprise', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Monalika Bhattarai', '9808016740', '', '', 'Stall H36A (2M X 2M)', 'Festive & Consumer Trade', 'Khaling Craft / Jishnu Ayurnidhi Enterprise at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H36A (2M X 2M).', '[]', '', '', '', 95, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-r-a-silver', 'R A Silver', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H36B (2M X 2M)', 'Festive & Consumer Trade', 'R A Silver at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H36B (2M X 2M).', '[]', '', '', '', 96, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-shreem-leather', 'Shreem Leather', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H37 (2M X 4M)', 'Festive & Consumer Trade', 'Shreem Leather at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H37 (2M X 4M).', '[]', '', '', '', 97, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-minnie', 'Minnie', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Nikita Karki', '', '', '', 'Stall H38 (2M X 2M)', 'Festive & Consumer Trade', 'Minnie at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H38 (2M X 2M).', '[]', '', '', '', 98, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-chitika-fashion', 'Chitika Fashion', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H39 (2M X 2M)', 'Festive & Consumer Trade', 'Chitika Fashion at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H39 (2M X 2M).', '[]', '', '', '', 99, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-sarangi-bedsheet', 'Sarangi Bedsheet', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H40 (2M X 2M)', 'Festive & Consumer Trade', 'Sarangi Bedsheet at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H40 (2M X 2M).', '[]', '', '', '', 100, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-jawa-hemp', 'Jawa Hemp', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H41 (2M X 2M)', 'Festive & Consumer Trade', 'Jawa Hemp at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H41 (2M X 2M).', '[]', '', '', '', 101, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-dmooster', 'Dmooster', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall H42 (2M X 2M)', 'Festive & Consumer Trade', 'Dmooster at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H42 (2M X 2M).', '[]', '', '', '', 102, v_edition_2026_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ex-2026-comfort-zone-kathmandu', 'Comfort Zone Kathmandu', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H43 (2M X 2M)', 'Festive & Consumer Trade', 'Comfort Zone Kathmandu at Stock Clearance 2026', 'Participating exhibitor at Stock Clearance (Dashain Fest 2026). Stall H43 (2M X 2M).', '[]', '', '', '', 103, v_edition_2026_id, NOW(), NOW(), 'APPROVED');

    RAISE NOTICE 'Successfully seeded Stock Clearance 2025 (35) and 2026 (104)';
END $$;
