-- Stock Clearance 2025 Exhibitors SQL Data
-- 105 Exhibitors

-- Clean up duplicate dashain-fest event if exists
DELETE FROM public."Exhibitor" WHERE "editionId" IN (SELECT id FROM public."ExhibitorEdition" WHERE "eventId" IN (SELECT id FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest'));
DELETE FROM public."ExhibitorEdition" WHERE "eventId" IN (SELECT id FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest');
DELETE FROM public."ExhibitorEvent" WHERE slug = 'dashain-fest';

-- Ensure Stock Clearance event exists
INSERT INTO public."ExhibitorEvent" (slug, title, "chronicleNumber", description, "previewImage", "order", "createdAt", "updatedAt")
VALUES ('stock-clearance', 'Stock Clearance', '04', 'Nepal''s premier consumer shopping, clearance festival, and festive carnival connecting leading manufacturers, retail distributors, and domestic brands directly with shoppers.', 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80', 3, NOW(), NOW())
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title;

-- Ensure Edition 2025 exists for Stock Clearance
DO $$
DECLARE
    v_event_id INT;
    v_edition_id INT;
BEGIN
    SELECT id INTO v_event_id FROM public."ExhibitorEvent" WHERE slug = 'stock-clearance';
    
    SELECT id INTO v_edition_id FROM public."ExhibitorEdition" WHERE "eventId" = v_event_id AND year = '2025';
    IF v_edition_id IS NULL THEN
        INSERT INTO public."ExhibitorEdition" (year, title, dates, venue, attendees, "previewImage", "order", "eventId", "createdAt", "updatedAt")
        VALUES ('2025', 'Edition 2025 (Dashain Fest)', 'Dashain Season 2025', 'Bhrikutimandap Exhibition Ground, Kathmandu', '120K+', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80', 2, v_event_id, NOW(), NOW())
        RETURNING id INTO v_edition_id;
    END IF;

    -- Remove earlier 2025 exhibitors
    DELETE FROM public."Exhibitor" WHERE "editionId" = v_edition_id;

    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('tera-collection', 'Tera Collection', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 1 (3M X 3M)', 'Festive & Consumer Trade', 'Tera Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 0, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nepal-cotton-house', 'Nepal Cotton House', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 2 (3M X 3M)', 'Festive & Consumer Trade', 'Nepal Cotton House at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 1, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('heera-enterprise-bangladesh', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 3 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 2, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('eras-feel', 'Eras Feel', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Manisha', '986-3253251', '', '', 'Stall 4 (3M X 3M)', 'Festive & Consumer Trade', 'Eras Feel at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 3, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('opseri-boutique-bangladesh', 'Opseri Boutique (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 5 (3M X 3M)', 'Festive & Consumer Trade', 'Opseri Boutique (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 4, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('kohinoor-knitwear-bangladesh', 'Kohinoor Knitwear (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 6 (3M X 3M)', 'Festive & Consumer Trade', 'Kohinoor Knitwear (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 5, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('soft-skin-pakistan', 'Soft Skin (Pakistan)', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 7 (3M X 3M)', 'Festive & Consumer Trade', 'Soft Skin (Pakistan) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 6, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('pinky-fashion', 'Pinky Fashion', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 8 (3M X 3M)', 'Festive & Consumer Trade', 'Pinky Fashion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 7, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('toys-world', 'Toys World', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall 9 (6M X 3M)', 'Festive & Consumer Trade', 'Toys World at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 8, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nihan-traders-china', 'Nihan Traders (China)', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 10 (6M X 3M)', 'Festive & Consumer Trade', 'Nihan Traders (China) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 9, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('bluemen-bangladesh', 'Bluemen (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 11 (3M X 3M)', 'Festive & Consumer Trade', 'Bluemen (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 10, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('heera-enterprise-bangladesh-stall-12-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 12 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 11, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('heera-enterprise-bangladesh-stall-13-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 13 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 12, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('heera-enterprise-bangladesh-stall-14-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 14 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 13, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('heera-enterprise-bangladesh-stall-15-1', 'Heera Enterprise (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 15 (3M X 3M)', 'Festive & Consumer Trade', 'Heera Enterprise (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 14, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('pakistan-pavilion', 'Pakistan Pavilion', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 16 (3M X 3M)', 'Festive & Consumer Trade', 'Pakistan Pavilion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 15, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('kiddo', 'Kiddo', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Suparbha Shrestha', '9841919262', '', '', 'Stall 17 (3M X 3M)', 'Festive & Consumer Trade', 'Kiddo at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 16, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('bangladesh-pavilion', 'Bangladesh Pavilion', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 18 (6M X 3M)', 'Festive & Consumer Trade', 'Bangladesh Pavilion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 17, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-nepal', 'Shoes Nepal', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Krishtina', '9811821331', '', '', 'Stall 19 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Nepal at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 18, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-expo-section-a', 'Shoes Expo Section A', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 20 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section A at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 19, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-expo-section-b', 'Shoes Expo Section B', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 21 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section B at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 20, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-expo-section-c', 'Shoes Expo Section C', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 22 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Expo Section C at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 21, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('saurab', 'Saurab', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 23 (6M X 3M)', 'Festive & Consumer Trade', 'Saurab at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 22, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('al-madina', 'Al-Madina', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 24 (6M X 3M)', 'Festive & Consumer Trade', 'Al-Madina at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 23, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-store', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 25 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 24, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-store-stall-26-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 26 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 25, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('your-readymade', 'Your Readymade', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 27 (3M X 3M)', 'Festive & Consumer Trade', 'Your Readymade at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 26, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nitya-traditional-trader', 'Nitya Traditional Trader', '/company/Screenshot%202025-12-28%20at%201.31.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 28 (3M X 3M)', 'Festive & Consumer Trade', 'Nitya Traditional Trader at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 27, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('bangladesh-trade-store', 'Bangladesh Trade Store', '/company/Screenshot%202025-12-28%20at%201.31.46%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 29 (3M X 3M)', 'Festive & Consumer Trade', 'Bangladesh Trade Store at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 28, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('mousami-saari-india-fairy-angel-bangladesh', 'Mousami Saari (India) / Fairy Angel (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 30 (6M X 3M)', 'Festive & Consumer Trade', 'Mousami Saari (India) / Fairy Angel (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 29, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('sandhya-furniture-india', 'Sandhya Furniture (India)', '/company/Screenshot%202025-12-28%20at%201.31.57%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 31 (6M X 3M)', 'Festive & Consumer Trade', 'Sandhya Furniture (India) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 30, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('simrik-collection', 'Simrik Collection', '/company/Screenshot%202025-12-28%20at%201.32.47%E2%80%AFPM.png', 'Monalika Bhattarai', '', '', '', 'Stall 32 (3M X 3M)', 'Festive & Consumer Trade', 'Simrik Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 31, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('k-nav-collection', 'K.nav Collection', '/company/Screenshot%202025-12-28%20at%201.32.58%E2%80%AFPM.png', 'Monalika Bhattarai', '9860286644', '', '', 'Stall 33 (3M X 3M)', 'Festive & Consumer Trade', 'K.nav Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 32, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('anish-clothing', 'Anish Clothing', '/company/Screenshot%202025-12-28%20at%201.33.04%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall 34 (3M X 3M)', 'Festive & Consumer Trade', 'Anish Clothing at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anish Shrestha.', '[]', '', '', '', 33, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-store-stall-35-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.33.10%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 35 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 34, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-store-stall-36-1', 'Shoes Store', '/company/Screenshot%202025-12-28%20at%201.33.20%E2%80%AFPM.png', 'Sarita Agrawal', '9808614696', '', '', 'Stall 36 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Store at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 35, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('arksh-group', 'Arksh Group', '/company/Screenshot%202025-12-28%20at%201.33.29%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 37 (6M X 3M)', 'Festive & Consumer Trade', 'Arksh Group at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 36, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('refer-lifestyle', 'Refer Lifestyle', '/company/Screenshot%202025-12-28%20at%201.33.34%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 38 (6M X 3M)', 'Festive & Consumer Trade', 'Refer Lifestyle at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 37, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-gallery-a', 'Shoes Gallery A', '/company/Screenshot%202025-12-28%20at%201.40.40%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 39 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery A at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 38, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-gallery-b', 'Shoes Gallery B', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 40 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery B at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 39, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-gallery-c', 'Shoes Gallery C', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 41 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery C at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 40, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shoes-gallery-d', 'Shoes Gallery D', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall 42 (3M X 3M)', 'Festive & Consumer Trade', 'Shoes Gallery D at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 41, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('made-in-bangladesh-bangladesh', 'Made in Bangladesh (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 43 (6M X 3M)', 'Festive & Consumer Trade', 'Made in Bangladesh (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 42, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('g-11-bangladesh', 'G-11 (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 44 (3M X 3M)', 'Festive & Consumer Trade', 'G-11 (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 43, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('barcilife-bangladesh', 'Barcilife (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 45 (3M X 3M)', 'Festive & Consumer Trade', 'Barcilife (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 44, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('a-p-zone', 'A.P Zone', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 46 (3M X 3M)', 'Festive & Consumer Trade', 'A.P Zone at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 45, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('milan-jutta-pasal', 'Milan Jutta Pasal', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 47 (3M X 3M)', 'Festive & Consumer Trade', 'Milan Jutta Pasal at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 46, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('milan-jutta-pasal-stall-48-1', 'Milan Jutta Pasal', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 48 (3M X 3M)', 'Festive & Consumer Trade', 'Milan Jutta Pasal at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 47, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('arohan-associate-bangladesh', 'Arohan Associate (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 49 (3M X 3M)', 'Festive & Consumer Trade', 'Arohan Associate (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 48, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('tera-collection-stall-50-1', 'Tera Collection', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 50 (3M X 3M)', 'Festive & Consumer Trade', 'Tera Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 49, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('mukti-clothing', 'Mukti Clothing', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 51 (6M X 3M)', 'Festive & Consumer Trade', 'Mukti Clothing at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 50, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('krisha-collection', 'Krisha Collection', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 52A (3M X 3M)', 'Festive & Consumer Trade', 'Krisha Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 51, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('sitara-bag-jewellry', 'Sitara Bag & Jewellry', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Meleena Kalikote', '9825755160', '', '', 'Stall 52B (3M X 3M)', 'Festive & Consumer Trade', 'Sitara Bag & Jewellry at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 52, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shree-collection', 'Shree Collection', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 53 (3M X 3M)', 'Festive & Consumer Trade', 'Shree Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 53, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('gopal-enterprises', 'Gopal Enterprises', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 54 (3M X 3M)', 'Festive & Consumer Trade', 'Gopal Enterprises at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 54, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('universal-packaging-industries-pvt-ltd', 'Universal Packaging Industries Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 55 (3M X 3M)', 'Festive & Consumer Trade', 'Universal Packaging Industries Pvt. Ltd at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 55, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('krisha-collection-hold', 'Krisha Collection (Hold)', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 56 (3M X 3M)', 'Festive & Consumer Trade', 'Krisha Collection (Hold) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 56, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('n-fashion', 'N Fashion', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 57 (3M X 3M)', 'Festive & Consumer Trade', 'N Fashion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 57, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nepal-wool-house', 'Nepal Wool House', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall 58 (3M X 3M)', 'Festive & Consumer Trade', 'Nepal Wool House at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 58, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('royal-furniture-udyog', 'Royal Furniture Udyog', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall 59 (6M X 3M)', 'Festive & Consumer Trade', 'Royal Furniture Udyog at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 59, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('asian-exclusive-bismillah-accessories-bangladesh', 'Asian Exclusive / Bismillah Accessories (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H1 (2M X 4M)', 'Festive & Consumer Trade', 'Asian Exclusive / Bismillah Accessories (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 60, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('karuka-lamiha-handicraft-bangladesh', 'Karuka / Lamiha Handicraft (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H2 (2M X 4M)', 'Festive & Consumer Trade', 'Karuka / Lamiha Handicraft (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 61, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('bangladesh-artisan-house', 'Bangladesh Artisan House', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H3 (2M X 4M)', 'Festive & Consumer Trade', 'Bangladesh Artisan House at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 62, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('europhoria-nepal', 'Europhoria Nepal', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H4 (2M X 2M)', 'Festive & Consumer Trade', 'Europhoria Nepal at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 63, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('wosa-wears', 'Wosa Wears', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H5 (2M X 2M)', 'Festive & Consumer Trade', 'Wosa Wears at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 64, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('anandi-jewellery', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H6 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 65, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('anandi-jewellery-stall-h7-1', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.41%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H7 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 66, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('anandi-jewellery-stall-h8-1', 'Anandi Jewellery', '/company/Screenshot%202025-12-28%20at%201.31.46%E2%80%AFPM.png', 'Monalika Bhattarai', '9702009121', '', '', 'Stall H8 (2M X 2M)', 'Festive & Consumer Trade', 'Anandi Jewellery at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 67, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('naya-naulo', 'Naya Naulo', '/company/Screenshot%202025-12-28%20at%201.31.52%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H9 (2M X 2M)', 'Festive & Consumer Trade', 'Naya Naulo at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 68, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('pathibhara-art-handicraft', 'Pathibhara Art Handicraft', '/company/Screenshot%202025-12-28%20at%201.31.57%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H10 (2M X 4M)', 'Festive & Consumer Trade', 'Pathibhara Art Handicraft at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 69, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ladies-bags-barsha-jung-chettri', 'Ladies Bags / Barsha Jung Chettri', '/company/Screenshot%202025-12-28%20at%201.32.47%E2%80%AFPM.png', 'Barsha Jung Chettri', '', '', '', 'Stall H11 (2M X 2M)', 'Festive & Consumer Trade', 'Ladies Bags / Barsha Jung Chettri at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 70, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('uma-collection', 'Uma Collection', '/company/Screenshot%202025-12-28%20at%201.32.58%E2%80%AFPM.png', 'Grishma Maharjan', '', '', '', 'Stall H12 (2M X 2M)', 'Festive & Consumer Trade', 'Uma Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 71, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('bishal-ayurveda', 'Bishal Ayurveda', '/company/Screenshot%202025-12-28%20at%201.33.04%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H13 (2M X 2M)', 'Festive & Consumer Trade', 'Bishal Ayurveda at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 72, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('arlens-leather-bangladesh', 'Arlens Leather (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.33.10%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H14 (2M X 2M)', 'Festive & Consumer Trade', 'Arlens Leather (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 73, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shine-chemical', 'Shine Chemical', '/company/Screenshot%202025-12-28%20at%201.33.20%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H15 (2M X 2M)', 'Festive & Consumer Trade', 'Shine Chemical at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 74, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nevan-collection', 'Nevan Collection', '/company/Screenshot%202025-12-28%20at%201.33.29%E2%80%AFPM.png', 'Grishma Maharjan', '9861285382', '', '', 'Stall H16 (2M X 2M)', 'Festive & Consumer Trade', 'Nevan Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 75, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nelli', 'Nelli', '/company/Screenshot%202025-12-28%20at%201.33.34%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H17 (2M X 2M)', 'Festive & Consumer Trade', 'Nelli at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 76, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('padma-chura', 'Padma Chura', '/company/Screenshot%202025-12-28%20at%201.40.40%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H18 (2M X 2M)', 'Festive & Consumer Trade', 'Padma Chura at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 77, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('adore-home-hold', 'Adore Home (Hold)', '/company/Screenshot%202025-12-28%20at%201.24.13%E2%80%AFPM.png', 'Grishma Maharjan', '9818021462', '', '', 'Stall H19 (2M X 2M)', 'Festive & Consumer Trade', 'Adore Home (Hold) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 78, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('dora-collection', 'Dora Collection', '/company/Screenshot%202025-12-28%20at%201.27.03%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H20 (2M X 4M)', 'Festive & Consumer Trade', 'Dora Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 79, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('kanak-wear', 'Kanak Wear', '/company/Screenshot%202025-12-28%20at%201.27.15%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H21 (2M X 4M)', 'Festive & Consumer Trade', 'Kanak Wear at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 80, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('casper-in-out-trading-pvt-ltd', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.27.31%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H22 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 81, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('poshakana-bangladesh', 'Poshakana (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.27.41%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H23 (2M X 2M)', 'Festive & Consumer Trade', 'Poshakana (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 82, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('moontain-creamery', 'Moontain Creamery', '/company/Screenshot%202025-12-28%20at%201.28.00%E2%80%AFPM.png', 'Grishma Maharjan', '9764799554', '', '', 'Stall H24 (2M X 2M)', 'Festive & Consumer Trade', 'Moontain Creamery at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 83, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('casper-in-out-trading-pvt-ltd-stall-h25-1', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.28.15%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H25 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 84, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('casper-in-out-trading-pvt-ltd-stall-h26-1', 'Casper In & Out Trading Pvt. Ltd', '/company/Screenshot%202025-12-28%20at%201.28.26%E2%80%AFPM.png', 'Monalika Bhattarai', '9801118491', '', '', 'Stall H26 (2M X 2M)', 'Festive & Consumer Trade', 'Casper In & Out Trading Pvt. Ltd at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 85, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('smart-corporation-bangladesh', 'Smart Corporation (Bangladesh)', '/company/Screenshot%202025-12-28%20at%201.28.37%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H27 (2M X 2M)', 'Festive & Consumer Trade', 'Smart Corporation (Bangladesh) at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 86, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('baladu', 'Baladu', '/company/Screenshot%202025-12-28%20at%201.28.44%E2%80%AFPM.png', 'Grishma Maharjan', '9709061047', '', '', 'Stall H28 (2M X 2M)', 'Festive & Consumer Trade', 'Baladu at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 87, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('pinky-fashion-stall-h29-1', 'Pinky Fashion', '/company/Screenshot%202025-12-28%20at%201.28.50%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H29 (2M X 2M)', 'Festive & Consumer Trade', 'Pinky Fashion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 88, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('nepali-maan-udyog', 'Nepali Maan Udyog', '/company/Screenshot%202025-12-28%20at%201.29.00%E2%80%AFPM.png', 'Grishma Maharjan', '9703093066', '', '', 'Stall H30 (2M X 2M)', 'Festive & Consumer Trade', 'Nepali Maan Udyog at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 89, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('baladu-stall-h31-1', 'Baladu', '/company/Screenshot%202025-12-28%20at%201.29.07%E2%80%AFPM.png', 'Grishma Maharjan', '9709061047', '', '', 'Stall H31 (2M X 2M)', 'Festive & Consumer Trade', 'Baladu at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Grishma Maharjan.', '[]', '', '', '', 90, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('suyog-marketing', 'Suyog Marketing', '/company/Screenshot%202025-12-28%20at%201.29.15%E2%80%AFPM.png', 'Malika Sangat', '9843456166', '', '', 'Stall H32 (2M X 2M)', 'Festive & Consumer Trade', 'Suyog Marketing at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 91, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('7-r-tatooz', '7 R Tatooz', '/company/Screenshot%202025-12-28%20at%201.29.23%E2%80%AFPM.png', 'Monalika Bhattarai', '9847293753', '', '', 'Stall H33 (2M X 2M)', 'Festive & Consumer Trade', '7 R Tatooz at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 92, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('jamuna-collection', 'Jamuna Collection', '/company/Screenshot%202025-12-28%20at%201.29.29%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H34 (2M X 2M)', 'Festive & Consumer Trade', 'Jamuna Collection at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 93, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('ujwol-boutique', 'Ujwol Boutique', '/company/Screenshot%202025-12-28%20at%201.29.38%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall H35 (2M X 2M)', 'Festive & Consumer Trade', 'Ujwol Boutique at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anish Shrestha.', '[]', '', '', '', 94, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('khaling-craft-jishnu-ayurnidhi-enterprise', 'Khaling Craft / Jishnu Ayurnidhi Enterprise', '/company/Screenshot%202025-12-28%20at%201.29.45%E2%80%AFPM.png', 'Monalika Bhattarai', '9808016740', '', '', 'Stall H36A (2M X 2M)', 'Festive & Consumer Trade', 'Khaling Craft / Jishnu Ayurnidhi Enterprise at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Monalika Bhattarai.', '[]', '', '', '', 95, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('r-a-silver', 'R A Silver', '/company/Screenshot%202025-12-28%20at%201.29.55%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H36B (2M X 2M)', 'Festive & Consumer Trade', 'R A Silver at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 96, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('shreem-leather', 'Shreem Leather', '/company/Screenshot%202025-12-28%20at%201.30.02%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H37 (2M X 4M)', 'Festive & Consumer Trade', 'Shreem Leather at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 97, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('minnie', 'Minnie', '/company/Screenshot%202025-12-28%20at%201.30.18%E2%80%AFPM.png', 'Nikita Karki', '', '', '', 'Stall H38 (2M X 2M)', 'Festive & Consumer Trade', 'Minnie at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anish Shrestha.', '[]', '', '', '', 98, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('chitika-fashion', 'Chitika Fashion', '/company/Screenshot%202025-12-28%20at%201.30.48%E2%80%AFPM.png', 'Anil Shrestha', '', '', '', 'Stall H39 (2M X 2M)', 'Festive & Consumer Trade', 'Chitika Fashion at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anil Shrestha.', '[]', '', '', '', 99, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('sarangi-bedsheet', 'Sarangi Bedsheet', '/company/Screenshot%202025-12-28%20at%201.30.54%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H40 (2M X 2M)', 'Festive & Consumer Trade', 'Sarangi Bedsheet at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 100, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('jawa-hemp', 'Jawa Hemp', '/company/Screenshot%202025-12-28%20at%201.31.11%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall H41 (2M X 2M)', 'Festive & Consumer Trade', 'Jawa Hemp at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Manita Shrestha.', '[]', '', '', '', 101, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('dmooster', 'Dmooster', '/company/Screenshot%202025-12-28%20at%201.31.16%E2%80%AFPM.png', 'Anish Shrestha', '', '', '', 'Stall H42 (2M X 2M)', 'Festive & Consumer Trade', 'Dmooster at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anish Shrestha.', '[]', '', '', '', 102, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('comfort-zone-kathmandu', 'Comfort Zone Kathmandu', '/company/Screenshot%202025-12-28%20at%201.31.30%E2%80%AFPM.png', 'Anup Shrestha', '', '', '', 'Stall H43 (2M X 2M)', 'Festive & Consumer Trade', 'Comfort Zone Kathmandu at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Octonorm Stall. Coordinated by Anup Shrestha.', '[]', '', '', '', 103, v_edition_id, NOW(), NOW(), 'APPROVED');
    INSERT INTO public."Exhibitor" (slug, name, logo, "contactPerson", contact, email, website, booth, category, tagline, description, photos, "videoUrl", "videoPoster", "videoTitle", "order", "editionId", "createdAt", "updatedAt", status)
    VALUES ('paasapi', 'Paasapi', '/company/Screenshot%202025-12-28%20at%201.31.35%E2%80%AFPM.png', 'Manita Shrestha', '', '', '', 'Stall Food Court (Special Area)', 'Festive & Consumer Trade', 'Paasapi at Stock Clearance 2025', 'Participating exhibitor at Stock Clearance (Dashain Fest) 2025. Stall Type: Food Court. Coordinated by Manita Shrestha.', '[]', '', '', '', 104, v_edition_id, NOW(), NOW(), 'APPROVED');

    RAISE NOTICE 'Successfully seeded 105 exhibitors for Stock Clearance 2025';
END $$;
